import type { Exercise } from '@/types';

export const EXERCISES: Exercise[] = [
  // ─── BRUST (20) ─────────────────────────────────────────────────
  {
    id: 'langhantel-bankdruecken', name: 'Langhantel-Bankdrücken',
    description: 'Die Königsübung für die Brust. Flach auf der Bank liegend, die Langhantel schulterbreit greifen und kontrolliert zur unteren Brust senken.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder', 'rotator-cuff', 'wrist'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '3-5 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Schulterblätter zusammenziehen und nach unten drücken', 'Füße fest auf dem Boden', 'Stange zur unteren Brust führen', 'Handgelenke gerade halten'],
    commonMistakes: ['Ellbogen zu weit abspreizen — 45-75° halten', 'Stange von der Brust abprallen lassen', 'Oberen Rücken nicht fest anspannen'],
    alternatives: ['kurzhantel-bankdruecken', 'schraegbank-langhantel', 'maschinen-brustdruecken'],
    pros: ['Höchste Gewichtsbelastung möglich', 'Hervorragend für Kraftaufbau', 'Trainiert mehrere Muskelgruppen gleichzeitig'],
    cons: ['Erfordert Spotter bei schweren Gewichten', 'Eingeschränkter Bewegungsumfang', 'Belastet Schultergelenk'],
  },
  {
    id: 'kurzhantel-bankdruecken', name: 'Kurzhantel-Bankdrücken',
    description: 'Größerer Bewegungsumfang als mit der Langhantel. Jeder Arm arbeitet unabhängig, was Kraftungleichgewichte ausgleicht.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder', 'wrist'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Kurzhanteln auf Brusthöhe starten', 'Ellbogen bei 45° halten', 'Kontrolliert absenken und explosiv drücken'],
    commonMistakes: ['Zu schnelles Absenken', 'Gewichte zusammenschlagen oben', 'Schultern hochziehen'],
    alternatives: ['langhantel-bankdruecken', 'maschinen-brustdruecken', 'liegestuetz'],
    pros: ['Größerer Bewegungsumfang', 'Gleicht Muskelungleichgewichte aus', 'Schulterfreundlicher'],
    cons: ['Weniger Gesamtgewicht möglich', 'Schwierigeres Ablegen bei schweren Gewichten', 'Erfordert mehr Stabilisation'],
  },
  {
    id: 'schraegbank-langhantel', name: 'Schrägbankdrücken Langhantel',
    description: 'Betont die obere Brust durch eine 30-45° Neigung der Bank. Wichtig für eine vollständige Brustentwicklung.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders', 'triceps'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '4-6', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Bank auf 30-45° einstellen', 'Stange zum oberen Brustbereich senken', 'Schulterblätter zusammen und unten'],
    commonMistakes: ['Bank zu steil eingestellt (>45°)', 'Stange zu hoch zum Hals senken', 'Po von der Bank heben'],
    alternatives: ['schraegbank-kurzhantel', 'kabelzug-ueberkreuzen-niedrig', 'smith-bankdruecken'],
    pros: ['Zielt auf obere Brust', 'Stärkt vorderen Deltamuskel', 'Guter Übertrag auf Schulterdrücken'],
    cons: ['Weniger Gewicht als flaches Bankdrücken', 'Höhere Schulterbelastung', 'Erfordert verstellbare Bank'],
  },
  {
    id: 'schraegbank-kurzhantel', name: 'Schrägbankdrücken Kurzhantel',
    description: 'Kombiniert die Vorteile der Schrägbank mit der freien Bewegung der Kurzhanteln für optimale obere Brustaktivierung.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders', 'triceps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['30-45° Neigung wählen', 'Kurzhanteln seitlich neben den Ohren absenken', 'Volle Dehnung unten anstreben'],
    commonMistakes: ['Zu steile Neigung', 'Kurzhanteln nicht tief genug senken', 'Schwungholen mit dem Körper'],
    alternatives: ['schraegbank-langhantel', 'kabelzug-ueberkreuzen-niedrig', 'liegestuetz'],
    pros: ['Größter ROM für obere Brust', 'Unilaterale Korrektur', 'Sehr schulterfreundlich'],
    cons: ['Schwierig in Position zu bringen', 'Begrenzte Maximalkraft', 'Stabilisationsanforderung hoch'],
  },
  {
    id: 'maschinen-brustdruecken', name: 'Maschinen-Brustdrücken',
    description: 'Geführte Bewegung an der Maschine, ideal für Anfänger und für Nachermüdung am Ende des Trainings.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Sitzhöhe einstellen — Griffe auf Brusthöhe', 'Schulterblätter an Polster pressen', 'Kontrollierte Bewegung'],
    commonMistakes: ['Falsche Sitzhöhe', 'Gewicht am Ende fallen lassen', 'Schultern hochziehen'],
    alternatives: ['langhantel-bankdruecken', 'kurzhantel-bankdruecken', 'liegestuetz'],
    pros: ['Sicherer ohne Spotter', 'Leicht zu erlernen', 'Gut für Nachermüdung'],
    cons: ['Weniger Stabilisatorenarbeit', 'Fester Bewegungsweg', 'Nicht in jedem Gym verfügbar'],
  },
  {
    id: 'kabelzug-brustfliegen', name: 'Kabelzug-Brustfliegen',
    description: 'Konstante Spannung durch den Kabelzug über den gesamten Bewegungsumfang. Hervorragend für die innere Brust.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Leichten Schritt nach vorne machen', 'Arme leicht gebeugt halten', 'Hände vor der Brust zusammenführen'],
    commonMistakes: ['Zu viel Gewicht — Technik leidet', 'Arme zu stark beugen', 'Schwungholen aus dem Körper'],
    alternatives: ['pec-deck', 'kurzhantel-fliegen-flach', 'kabelzug-ueberkreuzen-hoch'],
    pros: ['Konstante Spannung', 'Isoliert die Brust', 'Einstellbare Winkel'],
    cons: ['Wenig Gesamtbelastung', 'Erfordert Kabelzug', 'Schwer progressiv zu überlasten'],
  },
  {
    id: 'pec-deck', name: 'Pec-Deck-Maschine',
    description: 'Isolationsübung an der Butterfly-Maschine für maximale Brustkontraktion.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Ellbogen leicht gebeugt halten', 'Brust rausstrecken', 'Langsam und kontrolliert zurückführen'],
    commonMistakes: ['Zu viel Gewicht', 'Arme komplett strecken', 'Schultern nach vorne rollen'],
    alternatives: ['kabelzug-brustfliegen', 'kurzhantel-fliegen-flach'],
    pros: ['Einfach zu bedienen', 'Gute Isolation', 'Sicher für Anfänger'],
    cons: ['Fester Bewegungsweg', 'Nur in Studios verfügbar', 'Wenig funktionelle Übertragung'],
  },
  {
    id: 'liegestuetz', name: 'Liegestütz',
    description: 'Der Klassiker — eine der besten Körpergewichtsübungen für Brust, Schultern und Trizeps. Überall ausführbar.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders', 'core'], difficulty: 'beginner',
    equipment: ['bodyweight'], injuriesToAvoid: ['wrist', 'shoulder'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '5-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '12-20', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-25', rest: '45 sec', rir: 2 }, recomp: { sets: 4, reps: '12-20', rest: '60 sec', rir: 2 },
    },
    formCues: ['Körper bildet gerade Linie', 'Hände schulterbreit', 'Brust fast zum Boden senken', 'Core anspannen'],
    commonMistakes: ['Hüfte durchhängen lassen', 'Ellbogen zu weit abspreizen', 'Nicht tief genug gehen'],
    alternatives: ['kurzhantel-bankdruecken', 'maschinen-brustdruecken', 'diamant-liegestuetz'],
    pros: ['Überall ausführbar', 'Kein Equipment nötig', 'Trainiert Core mit'],
    cons: ['Begrenzte progressive Überlastung', 'Handgelenkbelastung', 'Für Fortgeschrittene zu leicht'],
  },
  {
    id: 'diamant-liegestuetz', name: 'Diamant-Liegestütz',
    description: 'Enge Handposition bildet eine Rautenform. Starke Trizeps- und innere Brustaktivierung.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate',
    equipment: ['bodyweight'], injuriesToAvoid: ['wrist', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '12-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Daumen und Zeigefinger bilden Diamant', 'Ellbogen eng am Körper', 'Brust zum Diamant senken'],
    commonMistakes: ['Hände zu weit vorne', 'Ellbogen abspreizen', 'Hüfte hochdrücken'],
    alternatives: ['enges-bankdruecken', 'liegestuetz', 'trizeps-dips'],
    pros: ['Starke Trizepsaktivierung', 'Kein Equipment nötig', 'Intensiviert Standard-Liegestütz'],
    cons: ['Hohe Handgelenkbelastung', 'Schwierig für Anfänger', 'Begrenzte Progression'],
  },
  {
    id: 'brust-dips', name: 'Dips (Brustfokus)',
    description: 'Vorgelehnte Dips mit breitem Griff betonen die untere Brust. Starke Compound-Übung für den gesamten Oberkörper.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate',
    equipment: ['bodyweight'], injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Oberkörper 30° nach vorne neigen', 'Ellbogen leicht abspreizen', 'Bis 90° oder tiefer absenken'],
    commonMistakes: ['Zu aufrecht bleiben (Trizeps-Dip)', 'Zu tiefes Absenken bei Schulterproblemen', 'Schwungholen'],
    alternatives: ['decline-bankdruecken', 'kurzhantel-bankdruecken', 'liegestuetz'],
    pros: ['Hohe Gesamtkörperaktivierung', 'Zusatzgewicht möglich', 'Funktionelle Drückkraft'],
    cons: ['Hohe Schulterbelastung', 'Nicht für Anfänger geeignet', 'Erfordert Dip-Station'],
  },
  {
    id: 'kurzhantel-fliegen-flach', name: 'Kurzhantel-Fliegen flach',
    description: 'Isolationsübung für die Brust mit Kurzhanteln auf der Flachbank. Dehnt die Brustmuskulatur unter Last.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Arme leicht gebeugt halten', 'Bogenförmige Bewegung', 'Dehnung in der Brust spüren', 'Kurzhanteln oben nicht zusammenschlagen'],
    commonMistakes: ['Arme zu stark beugen — wird zum Drücken', 'Zu schwer — Schulter überlastet', 'Zu schnelles Tempo'],
    alternatives: ['kabelzug-brustfliegen', 'pec-deck', 'schraegbank-kurzhantel-fliegen'],
    pros: ['Starke Dehnung', 'Gute Isolation', 'Variabel einsetzbar'],
    cons: ['Schulterbelastung in Endposition', 'Wenig Spannung oben', 'Schwer zu steigern'],
  },
  {
    id: 'schraegbank-kurzhantel-fliegen', name: 'Schrägbank Kurzhantel-Fliegen',
    description: 'Fliegen auf der Schrägbank für die obere Brustmuskulatur. Ideale Ergänzung zum Schrägbankdrücken.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Bank 30° einstellen', 'Bogenförmig nach oben führen', 'Ellbogen leicht gebeugt lassen'],
    commonMistakes: ['Bank zu steil', 'Gewicht zu schwer', 'Ruckhafte Bewegung'],
    alternatives: ['kabelzug-ueberkreuzen-niedrig', 'kurzhantel-fliegen-flach', 'pec-deck'],
    pros: ['Betont obere Brust', 'Gute Dehnung', 'Kombination aus Isolation + Schrägwinkel'],
    cons: ['Schwierig zu positionieren', 'Schulterbelastung', 'Begrenzte Last'],
  },
  {
    id: 'kabelzug-ueberkreuzen-hoch', name: 'Kabelzug-Überkreuzen von oben',
    description: 'Kabel von der oberen Position nach unten ziehen. Betont die untere und innere Brust.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Schritt nach vorne machen', 'Hände auf Bauchhöhe zusammenführen', 'Brust anspannen und halten'],
    commonMistakes: ['Zu viel Schwung', 'Arme zu stark beugen', 'Oberkörper zu stark vorbeugen'],
    alternatives: ['kabelzug-brustfliegen', 'kabelzug-ueberkreuzen-niedrig', 'pec-deck'],
    pros: ['Konstante Spannung', 'Gute Kontraktion', 'Einstellbare Winkel'],
    cons: ['Wenig Maximalkraft', 'Erfordert Kabelturm', 'Schwer zu überlasten'],
  },
  {
    id: 'kabelzug-ueberkreuzen-niedrig', name: 'Kabelzug-Überkreuzen von unten',
    description: 'Kabel von der unteren Position nach oben ziehen. Betont die obere Brust ähnlich wie Schrägbankdrücken.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Kabel unten einstellen', 'Hände auf Brusthöhe zusammenführen', 'Brust oben anspannen'],
    commonMistakes: ['Zu viel Schulterarbeit', 'Arme strecken statt beugen', 'Rücken nicht gerade halten'],
    alternatives: ['schraegbank-kurzhantel', 'kabelzug-ueberkreuzen-hoch', 'schraegbank-kurzhantel-fliegen'],
    pros: ['Betont obere Brust', 'Konstante Spannung', 'Schulterfreundlich'],
    cons: ['Erfordert Kabelturm', 'Wenig absolute Last', 'Technik muss erlernt werden'],
  },
  {
    id: 'decline-bankdruecken', name: 'Decline-Bankdrücken',
    description: 'Bankdrücken auf der Negativbank betont die untere Brust. Viele können hier mehr Gewicht bewegen als flach.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '4-6', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Bank auf 15-30° Decline einstellen', 'Stange zum unteren Brustbereich senken', 'Füße sicher fixieren'],
    commonMistakes: ['Zu steiler Decline', 'Kopfdruck durch Kopfüber-Lage', 'Keine Sicherung'],
    alternatives: ['brust-dips', 'kabelzug-ueberkreuzen-hoch', 'langhantel-bankdruecken'],
    pros: ['Mehr Gewicht als flach möglich', 'Weniger Schulterbelastung', 'Untere Brust Fokus'],
    cons: ['Unbequeme Position', 'Spotter wichtig', 'Blut steigt in Kopf'],
  },
  {
    id: 'kurzhantel-pullover', name: 'Kurzhantel-Pullover',
    description: 'Klassische Übung die Brust und Latissimus gleichzeitig dehnt und trainiert. Quer auf der Bank liegend ausführen.',
    primaryMuscle: 'chest', secondaryMuscles: ['lats', 'triceps'], difficulty: 'intermediate',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 3, reps: '10-15', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Quer auf Bank legen', 'Kurzhantel mit beiden Händen greifen', 'Arme leicht gebeugt über den Kopf führen', 'Dehnung spüren und zurückführen'],
    commonMistakes: ['Zu schwer — Ellbogen beugen sich zu stark', 'Hüfte absenken', 'Ruckhafte Bewegung'],
    alternatives: ['kabelzug-pullover-stehend', 'straight-arm-pulldown', 'kabelzug-brustfliegen'],
    pros: ['Dehnt Brustkorb', 'Trainiert Brust und Lat', 'Gute Ergänzung'],
    cons: ['Schwer zu isolieren', 'Schulterbelastung bei Überdehnung', 'Technik anspruchsvoll'],
  },
  {
    id: 'smith-bankdruecken', name: 'Smith-Maschinen-Bankdrücken',
    description: 'Geführtes Bankdrücken an der Smith-Maschine. Ideal für Anfänger oder zum sicheren Ausbelastung.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Bank so positionieren dass Stange über unterer Brust ist', 'Schulterblätter zusammen', 'Kontrolliert drücken'],
    commonMistakes: ['Bank falsch positioniert', 'Zu viel Vertrauen in Maschine — trotzdem sauber ausführen', 'Handgelenke abknicken'],
    alternatives: ['langhantel-bankdruecken', 'maschinen-brustdruecken', 'kurzhantel-bankdruecken'],
    pros: ['Sicher ohne Spotter', 'Einfach zu bedienen', 'Gut für Dropsets'],
    cons: ['Fester Bewegungsweg', 'Weniger Stabilisatorenarbeit', 'Weniger funktionell'],
  },
  {
    id: 'einarmiges-kabelzug-fliegen', name: 'Einarmiges Kabelzug-Fliegen',
    description: 'Unilaterales Kabelzug-Fliegen für maximale Brustkontraktion und Korrektur von Ungleichgewichten.',
    primaryMuscle: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'intermediate',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Freie Hand an Hüfte oder Maschine', 'Arm bogenförmig zur Mitte führen', 'Brust bewusst anspannen'],
    commonMistakes: ['Körper verdreht sich', 'Zu viel Schwung', 'Zu schweres Gewicht'],
    alternatives: ['kabelzug-brustfliegen', 'pec-deck', 'kurzhantel-fliegen-flach'],
    pros: ['Maximale Kontraktion', 'Korrigiert Ungleichgewichte', 'Gute Mind-Muscle-Connection'],
    cons: ['Dauert doppelt so lang', 'Wenig Gesamtlast', 'Erfordert Kabelzug'],
  },
  {
    id: 'negatives-bankdruecken', name: 'Negatives Bankdrücken (Exzentrisch)',
    description: 'Nur die exzentrische Phase des Bankdrückens mit übermaximaler Last. Extrem effektiv für Kraftdurchbrüche.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'advanced',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '2-3', rest: '4 min', rir: 0 }, hypertrophy: { sets: 3, reps: '3-5', rest: '3 min', rir: 0 },
      definition: { sets: 2, reps: '4-6', rest: '3 min', rir: 1 }, recomp: { sets: 3, reps: '3-5', rest: '3 min', rir: 0 },
    },
    formCues: ['Zwei Spotter nötig', 'Nur langsam absenken (4-6 Sekunden)', 'Spotter helfen beim Hochdrücken'],
    commonMistakes: ['Ohne Spotter ausführen', 'Gewicht zu schnell senken', 'Zu häufig einsetzen'],
    alternatives: ['langhantel-bankdruecken', 'smith-bankdruecken', 'maschinen-brustdruecken'],
    pros: ['Übermaximale Belastung', 'Durchbricht Plateaus', 'Stärkt exzentrische Kraft'],
    cons: ['Erfordert Spotter', 'Hohes Verletzungsrisiko', 'Starker Muskelkater'],
  },
  {
    id: 'ring-liegestuetz', name: 'Ring-Liegestütz',
    description: 'Liegestütz an Gymnastikringen für maximale Instabilität und Brustaktivierung.',
    primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'shoulders', 'core'], difficulty: 'advanced',
    equipment: ['bodyweight'], injuriesToAvoid: ['shoulder', 'wrist'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Ringe schulterbreit einstellen', 'Ringe nach außen drehen oben (Turn Out)', 'Core maximal anspannen'],
    commonMistakes: ['Ringe schwingen lassen', 'Schultern hochziehen', 'Core nicht anspannen'],
    alternatives: ['liegestuetz', 'kurzhantel-bankdruecken', 'brust-dips'],
    pros: ['Maximale Stabilisatorenarbeit', 'Tiefere Dehnung möglich', 'Funktionelle Kraft'],
    cons: ['Ringe nötig', 'Sehr anspruchsvoll', 'Nicht für Anfänger'],
  },
  // ─── LATISSIMUS / RÜCKEN BREITE (15) ────────────────────────────
  {
    id: 'klimmzug-breit', name: 'Klimmzug breit',
    description: 'Der König der Rückenübungen. Breiter Obergriff für maximale Latissimus-Aktivierung.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'back', 'core'], difficulty: 'intermediate',
    equipment: ['bodyweight'], injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '8-12', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Breiter als schulterbreit greifen', 'Brust zur Stange ziehen', 'Schulterblätter zusammenziehen', 'Kontrolliert ablassen'],
    commonMistakes: ['Schwungholen (Kipping)', 'Nicht voll aushängen', 'Nur halb hochziehen'],
    alternatives: ['latziehen-breit', 'kinnzug-eng', 'klimmzug-neutral'],
    pros: ['Beste Lat-Übung', 'Kein Equipment nötig', 'Hohe Muskelaktivierung'],
    cons: ['Schwer für Anfänger', 'Gewichtszunahme erschwert es', 'Progression langsam'],
  },
  {
    id: 'kinnzug-eng', name: 'Kinnzug eng (Untergriff)',
    description: 'Enger Untergriff aktiviert Bizeps stärker und ermöglicht mehr Wiederholungen als der breite Klimmzug.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'back'], difficulty: 'intermediate',
    equipment: ['bodyweight'], injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '4-6', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Schulterbreit im Untergriff', 'Brust zur Stange', 'Ellbogen nach hinten ziehen'],
    commonMistakes: ['Nur Bizeps benutzen', 'Schwungholen', 'Schultern hochziehen'],
    alternatives: ['klimmzug-breit', 'latziehen-eng', 'kabelzug-curls'],
    pros: ['Mehr Bizepsarbeit', 'Meist mehr Wiederholungen', 'Schulterfreundlicher'],
    cons: ['Weniger Lat-Isolation', 'Bizeps ermüdet zuerst', 'Handgelenkbelastung'],
  },
  {
    id: 'latziehen-breit', name: 'Latzug breit',
    description: 'Maschinenalternative zum Klimmzug. Einstellbare Last ermöglicht präzise Progression.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'back'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Breit greifen', 'Stange zur oberen Brust ziehen', 'Schulterblätter aktiv zusammenziehen', 'Kontrolliert zurückführen'],
    commonMistakes: ['Stange in den Nacken ziehen', 'Zu weit nach hinten lehnen', 'Schwungholen'],
    alternatives: ['klimmzug-breit', 'latziehen-eng', 'latziehen-einarmig'],
    pros: ['Einstellbare Last', 'Gut für Anfänger', 'Präzise Progression'],
    cons: ['Weniger Stabilisatorenarbeit', 'Geringere Gesamtaktivierung', 'Maschinenabhängig'],
  },
  {
    id: 'latziehen-eng', name: 'Latzug eng (V-Griff)',
    description: 'Enger V-Griff am Latzug für mehr Rückendicke und Bizepsarbeit.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'back'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['V-Griff mit neutralem Griff', 'Zur oberen Brust ziehen', 'Ellbogen eng am Körper'],
    commonMistakes: ['Zu viel Schwung', 'Griff zu weit vom Körper', 'Nicht voll strecken oben'],
    alternatives: ['kinnzug-eng', 'latziehen-breit', 'sitzend-kabelzug-rudern'],
    pros: ['Mehr Bizeps', 'Schulterschonend', 'Guter Lat-Stretch'],
    cons: ['Weniger Lat-Breite', 'Bizeps limitiert oft', 'Maschinenabhängig'],
  },
  {
    id: 'latziehen-einarmig', name: 'Einarmiger Latzug',
    description: 'Unilateraler Latzug für maximale Lat-Kontraktion und Beseitigung von Kraftungleichgewichten.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps'], difficulty: 'intermediate',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '6-8', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: ['D-Griff verwenden', 'Ellbogen zur Hüfte ziehen', 'Lat bewusst anspannen'],
    commonMistakes: ['Körper verdreht sich', 'Bizeps übernimmt', 'Zu schnelles Tempo'],
    alternatives: ['latziehen-breit', 'einarmiges-kurzhantel-rudern', 'kabelzug-rudern-einarmig'],
    pros: ['Maximale Kontraktion', 'Behebt Ungleichgewichte', 'Gute Mind-Muscle-Connection'],
    cons: ['Doppelte Trainingszeit', 'Weniger absolute Last', 'Erfordert Kabelzug'],
  },
  {
    id: 'kabelzug-pullover-stehend', name: 'Kabelzug-Pullover stehend',
    description: 'Stehende Pullover-Variante am Kabelzug. Konstante Spannung über den gesamten Bewegungsumfang.',
    primaryMuscle: 'lats', secondaryMuscles: ['chest', 'triceps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Geradengriff oder Seil verwenden', 'Leicht vorbeugen', 'Stange zum Oberschenkel ziehen', 'Arme fast gestreckt halten'],
    commonMistakes: ['Arme beugen', 'Aus der Hüfte schwingen', 'Zu nah am Kabel stehen'],
    alternatives: ['kurzhantel-pullover', 'straight-arm-pulldown', 'latziehen-breit'],
    pros: ['Konstante Spannung', 'Isoliert Lat', 'Schulterfreundlich'],
    cons: ['Wenig Last', 'Erfordert Kabelzug', 'Technik muss erlernt werden'],
  },
  {
    id: 'einarmiges-kurzhantel-rudern', name: 'Einarmiges Kurzhantel-Rudern',
    description: 'Fundamentale Ruderübung. Eine Hand und Knie auf der Bank, die andere Seite rudert.',
    primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'back', 'traps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Rücken parallel zum Boden', 'Ellbogen eng am Körper ziehen', 'Schulterblatt zusammenziehen oben', 'Kurzhantel zur Hüfte ziehen'],
    commonMistakes: ['Rücken runden', 'Aus der Schulter ziehen', 'Rotation im Oberkörper'],
    alternatives: ['langhantel-rudern', 'kabelzug-rudern-einarmig', 'meadows-row'],
    pros: ['Unilateral — behebt Dysbalancen', 'Schont unteren Rücken', 'Hohe Last möglich'],
    cons: ['Zeitaufwändiger', 'Bankplatz nötig', 'Tendenz zum Schwungholen'],
  },
  {
    id: 'langhantel-rudern', name: 'Langhantel-Rudern vorgebeugt',
    description: 'Schwere Compound-Übung für den gesamten Rücken. Hüftbreiter Stand, vorgebeugt, zur unteren Brust rudern.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps', 'traps', 'core'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['45° Vorbeuge', 'Stange zum Bauchnabel ziehen', 'Schulterblätter zusammen oben', 'Rücken gerade halten'],
    commonMistakes: ['Rücken runden', 'Zu aufrecht stehen', 'Schwungholen mit Oberkörper'],
    alternatives: ['einarmiges-kurzhantel-rudern', 't-bar-rudern', 'pendlay-row'],
    pros: ['Hohe Gesamtbelastung', 'Trainiert ganzen Rücken', 'Guter Kraftaufbau'],
    cons: ['Hohe Belastung unterer Rücken', 'Technik anspruchsvoll', 'Ermüdend für Haltemuskulatur'],
  },
  {
    id: 'sitzend-kabelzug-rudern', name: 'Sitzendes Kabelzug-Rudern',
    description: 'Rudern am Kabelzug im Sitzen mit V-Griff. Schont den unteren Rücken durch gestützte Position.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps', 'traps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Aufrecht sitzen', 'V-Griff zum Bauch ziehen', 'Ellbogen eng am Körper', 'Brust rausstrecken'],
    commonMistakes: ['Zu weit nach hinten lehnen', 'Rücken runden in Startposition', 'Schwungholen'],
    alternatives: ['langhantel-rudern', 'einarmiges-kurzhantel-rudern', 'maschinen-rudern'],
    pros: ['Schont unteren Rücken', 'Konstante Spannung', 'Anfängerfreundlich'],
    cons: ['Weniger Gesamtkörperaktivierung', 'Maschinenabhängig', 'Weniger funktionell'],
  },
  {
    id: 't-bar-rudern', name: 'T-Bar-Rudern',
    description: 'Schweres Rudern an der T-Bar oder Landmine. Ermöglicht hohe Lasten bei stabilerer Position.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps', 'traps'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Brust gegen Polster pressen (falls vorhanden)', 'V-Griff um die Stange', 'Zur Brust ziehen'],
    commonMistakes: ['Zu aufrecht stehen', 'Rücken runden', 'Nur Arme benutzen'],
    alternatives: ['langhantel-rudern', 'einarmiges-kurzhantel-rudern', 'maschinen-rudern'],
    pros: ['Neutraler Griff schont Handgelenke', 'Schwere Lasten möglich', 'Stabile Position'],
    cons: ['Nicht in jedem Gym', 'Weniger ROM', 'Unterer Rücken belastet'],
  },
  {
    id: 'maschinen-rudern', name: 'Maschinen-Rudern',
    description: 'Geführtes Rudern an der Maschine. Perfekt für Anfänger und Nachermüdung.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Brustpolster einstellen', 'Griffe zum Bauch ziehen', 'Schulterblätter zusammenziehen'],
    commonMistakes: ['Zu weit nach hinten lehnen', 'Nur Arme benutzen', 'Zu schnelles Tempo'],
    alternatives: ['sitzend-kabelzug-rudern', 'langhantel-rudern', 'einarmiges-kurzhantel-rudern'],
    pros: ['Sehr sicher', 'Leicht zu erlernen', 'Gut für Nachermüdung'],
    cons: ['Wenig Stabilisatorenarbeit', 'Fester Bewegungsweg', 'Maschinenabhängig'],
  },
  {
    id: 'straight-arm-pulldown', name: 'Straight-Arm-Pulldown',
    description: 'Isolationsübung für den Lat am Kabelzug mit gestreckten Armen. Eliminiert Bizeps-Beteiligung.',
    primaryMuscle: 'lats', secondaryMuscles: ['triceps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Leicht vorbeugen', 'Arme fast gestreckt halten', 'Stange bis zum Oberschenkel drücken', 'Lat bewusst anspannen'],
    commonMistakes: ['Arme beugen', 'Aus den Schultern ziehen', 'Zu viel Gewicht'],
    alternatives: ['kabelzug-pullover-stehend', 'kurzhantel-pullover', 'latziehen-breit'],
    pros: ['Isoliert Lat ohne Bizeps', 'Gute Mind-Muscle-Connection', 'Aufwärmübung'],
    cons: ['Wenig absolute Last', 'Erfordert Kabelzug', 'Nur Isolation'],
  },
  {
    id: 'pendlay-row', name: 'Pendlay Row',
    description: 'Explosives Rudern vom Boden. Stange wird bei jeder Wiederholung abgelegt. Maximale Kraftentwicklung.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps', 'traps', 'core'], difficulty: 'advanced',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-8', rest: '2 min', rir: 2 },
      definition: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, recomp: { sets: 4, reps: '6-8', rest: '2 min', rir: 2 },
    },
    formCues: ['Oberkörper parallel zum Boden', 'Explosiv zur Brust ziehen', 'Stange bei jeder WH ablegen', 'Rücken gerade halten'],
    commonMistakes: ['Oberkörper zu aufrecht', 'Nicht vollständig ablegen', 'Rücken runden'],
    alternatives: ['langhantel-rudern', 't-bar-rudern', 'einarmiges-kurzhantel-rudern'],
    pros: ['Maximale Explosivkraft', 'Volle ROM', 'Kein Dehnreflex-Schummeln'],
    cons: ['Hohe Technik-Anforderung', 'Belastung unterer Rücken', 'Laut im Studio'],
  },
  {
    id: 'bruststuetz-rudern', name: 'Brustgestütztes Kurzhantel-Rudern',
    description: 'Rudern mit Brustauflage auf der Schrägbank. Eliminiert Schwung und schont den unteren Rücken.',
    primaryMuscle: 'lats', secondaryMuscles: ['back', 'biceps', 'traps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Brust auf Schrägbank legen', 'Kurzhanteln seitlich hängen lassen', 'Zur Hüfte ziehen', 'Schulterblätter zusammen oben'],
    commonMistakes: ['Brust vom Polster heben', 'Zu schwer — Schwungholen', 'Nicht vollständig strecken unten'],
    alternatives: ['einarmiges-kurzhantel-rudern', 'maschinen-rudern', 'sitzend-kabelzug-rudern'],
    pros: ['Kein Schwungholen möglich', 'Schont unteren Rücken', 'Isoliert Rücken'],
    cons: ['Brustpolster kann unbequem sein', 'Weniger absolute Last', 'Bank-Setup nötig'],
  },
  // ─── RÜCKEN DICKE (15) ──────────────────────────────────────────
  {
    id: 'klimmzug-neutral', name: 'Klimmzug neutraler Griff',
    description: 'Klimmzug mit parallelem Griff. Schont die Schultern und aktiviert Lat und Bizeps gleichermaßen.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'biceps'], difficulty: 'intermediate',
    equipment: ['bodyweight'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '4-6', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '8-12', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Parallelen Griff verwenden', 'Brust hoch', 'Schulterblätter zusammen'],
    commonMistakes: ['Schwungholen', 'Nicht voll strecken', 'Nur halb hochziehen'],
    alternatives: ['klimmzug-breit', 'kinnzug-eng', 'latziehen-eng'],
    pros: ['Schulterfreundlichster Griff', 'Gute Lat + Bizeps Aktivierung', 'Natürliche Handposition'],
    cons: ['Spezialgriff nötig', 'Weniger Lat-Breite', 'Nicht überall verfügbar'],
  },
  {
    id: 'langhantel-rudern-untergriffen', name: 'Langhantel-Rudern Untergriff',
    description: 'Rudern mit Untergriff für mehr Bizeps-Aktivierung und stärkere untere Lat-Aktivierung.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'biceps', 'traps'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back', 'wrist'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Schulterbreiter Untergriff', 'Stange zum Bauchnabel', '45° Oberkörperneigung'],
    commonMistakes: ['Handgelenke knicken ab', 'Rücken runden', 'Zu viel Bizeps'],
    alternatives: ['langhantel-rudern', 'sitzend-kabelzug-rudern', 'kinnzug-eng'],
    pros: ['Mehr Bizepsarbeit', 'Stärkere untere Lat-Aktivierung', 'Hohe Lasten möglich'],
    cons: ['Handgelenkbelastung', 'Bizeps limitiert', 'Technik anspruchsvoll'],
  },
  {
    id: 'kabelzug-rudern-weit', name: 'Kabelzug-Rudern weiter Griff',
    description: 'Sitzendes Kabelrudern mit breitem Griff für Rückenbreite und obere Rückenaktivierung.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'traps', 'biceps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Breiten Griff verwenden', 'Zum oberen Bauch ziehen', 'Ellbogen weit abspreizen'],
    commonMistakes: ['Griff zu eng', 'Zu weit nach hinten lehnen', 'Schultern hochziehen'],
    alternatives: ['sitzend-kabelzug-rudern', 'langhantel-rudern', 'maschinen-rudern'],
    pros: ['Oberer Rücken Fokus', 'Einstellbar', 'Schont unteren Rücken'],
    cons: ['Weniger Lat-Fokus', 'Maschinenabhängig', 'Braucht breiten Griff'],
  },
  {
    id: 'rueckenstrecker', name: 'Rückenstrecker (Hyperextension)',
    description: 'Stärkt den unteren Rücken, Gesäß und hintere Kette am 45°-Polster.',
    primaryMuscle: 'back', secondaryMuscles: ['glutes', 'hamstrings'], difficulty: 'beginner',
    equipment: ['bodyweight'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Hüfte auf Polster', 'Kontrolliert absenken', 'Bis zur geraden Linie aufrichten', 'Nicht überstrecken'],
    commonMistakes: ['Zu weit überstrecken', 'Ruckhafte Bewegung', 'Hände im Nacken drücken'],
    alternatives: ['good-morning', 'hyperextension-hamstrings', 'rumaenisches-kreuzheben'],
    pros: ['Stärkt unteren Rücken', 'Anfängerfreundlich', 'Präventiv gegen Rückenschmerzen'],
    cons: ['Kann bei falscher Technik schaden', 'Begrenzte Progression', 'Monoton'],
  },
  {
    id: 'meadows-row', name: 'Meadows Row',
    description: 'Einarmiges Rudern an der Landmine seitlich. Benannt nach John Meadows — einzigartiger Zugwinkel.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'biceps', 'traps'], difficulty: 'advanced',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Seitlich zur Landmine stehen', 'Dickes Ende greifen', 'Explosiv zur Hüfte ziehen'],
    commonMistakes: ['Falsche Positionierung', 'Zu viel Rotation', 'Griff rutscht'],
    alternatives: ['einarmiges-kurzhantel-rudern', 'kabelzug-rudern-einarmig', 'langhantel-rudern'],
    pros: ['Einzigartiger Winkel', 'Starke Lat-Kontraktion', 'Variation im Training'],
    cons: ['Technik schwierig', 'Landmine nötig', 'Griff unangenehm'],
  },
  {
    id: 'kabelzug-rudern-einarmig', name: 'Einarmiges Kabelzug-Rudern',
    description: 'Unilaterales Rudern am Kabelzug für konstante Spannung und Ungleichgewichts-Korrektur.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'biceps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '6-8', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: ['D-Griff verwenden', 'Ellbogen eng ziehen', 'Schulterblatt zusammenziehen'],
    commonMistakes: ['Körper rotiert', 'Schwungholen', 'Bizeps übernimmt'],
    alternatives: ['einarmiges-kurzhantel-rudern', 'latziehen-einarmig', 'sitzend-kabelzug-rudern'],
    pros: ['Konstante Spannung', 'Behebt Dysbalancen', 'Vielseitig einsetzbar'],
    cons: ['Weniger Last', 'Zeitaufwändig', 'Kabelzug nötig'],
  },
  {
    id: 'kabelzug-face-pull', name: 'Face Pull',
    description: 'Seilzug zum Gesicht für hintere Schulter, Rotatorenmanschette und oberen Rücken.',
    primaryMuscle: 'back', secondaryMuscles: ['shoulders', 'traps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 4, reps: '15-20', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '15-20', rest: '60 sec', rir: 2 },
    },
    formCues: ['Seil auf Gesichtshöhe einstellen', 'Zum Gesicht ziehen', 'Ellbogen hoch halten', 'Außenrotation am Ende'],
    commonMistakes: ['Zu schwer', 'Ellbogen fallen lassen', 'Kein Squeeze am Ende'],
    alternatives: ['vorgeb-kurzhantel-heben', 'band-face-pull', 'umgekehrtes-fliegen-maschine'],
    pros: ['Exzellent für Schultergesundheit', 'Stärkt Rotatorenmanschette', 'Verbessert Haltung'],
    cons: ['Wenig Hypertrophie-Stimulus', 'Oft falsch ausgeführt', 'Kabelzug nötig'],
  },
  {
    id: 'umgekehrtes-fliegen-maschine', name: 'Umgekehrtes Fliegen (Reverse Pec-Deck)',
    description: 'Rückwärts an der Pec-Deck-Maschine für hintere Schulter und oberen Rücken.',
    primaryMuscle: 'back', secondaryMuscles: ['shoulders', 'traps'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Brust gegen Polster', 'Arme leicht gebeugt', 'Schulterblätter zusammenziehen'],
    commonMistakes: ['Zu schwer', 'Arme statt Rücken arbeiten', 'Momentum nutzen'],
    alternatives: ['kabelzug-face-pull', 'vorgeb-kurzhantel-heben', 'vorgeb-kabelzug-heben'],
    pros: ['Einfach zu bedienen', 'Isoliert hintere Schulter', 'Sicher'],
    cons: ['Maschinenabhängig', 'Begrenzte Last', 'Nur Isolation'],
  },
  {
    id: 'renegade-row', name: 'Renegade Row',
    description: 'Rudern in der Liegestützposition. Trainiert Rücken, Core und Stabilität gleichzeitig.',
    primaryMuscle: 'back', secondaryMuscles: ['core', 'lats', 'biceps'], difficulty: 'advanced',
    equipment: ['dumbbell'], injuriesToAvoid: ['wrist', 'lower-back'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '5-8', rest: '2 min', rir: 2 }, hypertrophy: { sets: 3, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Liegestützposition auf Kurzhanteln', 'Hüfte stabil halten', 'Abwechselnd rudern', 'Core maximal anspannen'],
    commonMistakes: ['Hüfte rotiert', 'Zu schwere Gewichte', 'Füße zu eng'],
    alternatives: ['einarmiges-kurzhantel-rudern', 'plank', 'langhantel-rudern'],
    pros: ['Extreme Core-Anforderung', 'Funktionelle Ganzkörperübung', 'Zeiteffizient'],
    cons: ['Wenig Rücken-Isolation', 'Handgelenkbelastung', 'Schwierig auszuführen'],
  },
  {
    id: 'good-morning', name: 'Good Morning',
    description: 'Langhantel auf dem Rücken, Oberkörper nach vorne beugen. Stärkt hintere Kette und unteren Rücken.',
    primaryMuscle: 'back', secondaryMuscles: ['hamstrings', 'glutes'], difficulty: 'advanced',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '5-8', rest: '3 min', rir: 2 }, hypertrophy: { sets: 3, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Stange auf hinterem Deltamuskel', 'Knie leicht gebeugt', 'Aus der Hüfte beugen', 'Rücken gerade halten'],
    commonMistakes: ['Rücken runden', 'Knie sperren', 'Zu viel Gewicht'],
    alternatives: ['rumaenisches-kreuzheben', 'rueckenstrecker', 'hyperextension-hamstrings'],
    pros: ['Starke hintere Kette', 'Verbessert Kniebeuge-Technik', 'Funktionell'],
    cons: ['Hohes Verletzungsrisiko', 'Erfordert gute Mobilität', 'Nicht für Anfänger'],
  },
  {
    id: 'kreuzheben', name: 'Konventionelles Kreuzheben',
    description: 'Die ultimative Ganzkörperübung. Stange vom Boden aufheben mit geradem Rücken. Trainiert praktisch jeden Muskel.',
    primaryMuscle: 'back', secondaryMuscles: ['hamstrings', 'glutes', 'quads', 'traps', 'core'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back', 'knee'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '4 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-8', rest: '3 min', rir: 2 },
      definition: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, recomp: { sets: 4, reps: '5-8', rest: '3 min', rir: 2 },
    },
    formCues: ['Stange über Mittelfuß', 'Schulterbreit greifen', 'Brust raus, Rücken gerade', 'Hüfte und Knie gleichzeitig strecken'],
    commonMistakes: ['Rücken runden', 'Stange zu weit vom Körper', 'Hyperextension oben', 'Knie fallen nach innen'],
    alternatives: ['sumo-kreuzheben', 'rumaenisches-kreuzheben', 'rack-pull'],
    pros: ['Maximale Ganzkörperaktivierung', 'Bester Kraftaufbau', 'Funktionell'],
    cons: ['Hohes Technik-Erfordernis', 'Belastung unterer Rücken', 'Sehr ermüdend'],
  },
  {
    id: 'sumo-kreuzheben', name: 'Sumo-Kreuzheben',
    description: 'Weiter Stand, Hände zwischen den Knien. Reduziert Belastung des unteren Rückens, betont Beine mehr.',
    primaryMuscle: 'back', secondaryMuscles: ['quads', 'glutes', 'hamstrings', 'traps'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back', 'hip', 'knee'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '4 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-8', rest: '3 min', rir: 2 },
      definition: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, recomp: { sets: 4, reps: '5-8', rest: '3 min', rir: 2 },
    },
    formCues: ['Breiter Stand, Zehen nach außen', 'Hände schulterbreit', 'Knie über Zehen drücken', 'Hüfte zur Stange bringen'],
    commonMistakes: ['Stand zu breit', 'Hüfte schießt hoch', 'Knie fallen nach innen'],
    alternatives: ['kreuzheben', 'rumaenisches-kreuzheben', 'beinpresse'],
    pros: ['Weniger Belastung unterer Rücken', 'Mehr Quadrizeps', 'Aufrechter Oberkörper'],
    cons: ['Erfordert Hüftmobilität', 'Langes Setup', 'Adduktoren-Belastung'],
  },
  {
    id: 'rack-pull', name: 'Rack Pull',
    description: 'Kreuzheben aus dem Rack ab Kniehöhe. Fokussiert oberen Rücken und Trapez mit übermaximalen Lasten.',
    primaryMuscle: 'back', secondaryMuscles: ['traps', 'glutes', 'hamstrings'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '3-5', rest: '4 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-8', rest: '3 min', rir: 2 },
      definition: { sets: 3, reps: '8-10', rest: '2 min', rir: 2 }, recomp: { sets: 4, reps: '5-8', rest: '3 min', rir: 2 },
    },
    formCues: ['Sicherheitsnadeln auf Kniehöhe', 'Gleiche Technik wie Kreuzheben', 'Schulterblätter zusammen oben'],
    commonMistakes: ['Zu tief einstellen', 'Hyperextension', 'Rücken runden'],
    alternatives: ['kreuzheben', 'langhantel-shrug', 'sumo-kreuzheben'],
    pros: ['Übermaximale Lasten', 'Stärkt Lockout', 'Weniger untere Rückenbelastung'],
    cons: ['Geringerer ROM', 'Schienbeinprellungen', 'Power Rack nötig'],
  },
  {
    id: 'bauchgestuetztes-rudern', name: 'Bauchgestütztes Seal Row',
    description: 'Rudern auf einer erhöhten Bank liegend. Kein Schwung möglich — pure Rückenarbeit.',
    primaryMuscle: 'back', secondaryMuscles: ['lats', 'biceps', 'traps'], difficulty: 'intermediate',
    equipment: ['dumbbell'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Bauch auf erhöhte Bank', 'Arme hängen lassen', 'Kurzhanteln zur Hüfte ziehen', 'Schulterblätter zusammen'],
    commonMistakes: ['Bank zu niedrig', 'Brust vom Polster heben', 'Nicht voll strecken'],
    alternatives: ['bruststuetz-rudern', 'einarmiges-kurzhantel-rudern', 'maschinen-rudern'],
    pros: ['Null Schwungmöglichkeit', 'Schont unteren Rücken', 'Reine Rückenarbeit'],
    cons: ['Spezielle Aufstellung nötig', 'Unbequem', 'Begrenzte Last'],
  },
  // ─── SCHULTERN (20) ─────────────────────────────────────────────
  {
    id: 'langhantel-schulter-druecken', name: 'Langhantel-Schulterdrücken',
    description: 'Stehend oder sitzend die Langhantel über den Kopf drücken. Fundamentale Compound-Übung für die Schultern.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps', 'core', 'traps'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder', 'lower-back'],
    recommendedSetsReps: {
      strength: { sets: 5, reps: '3-5', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '6-10', rest: '90 sec', rir: 2 },
    },
    formCues: ['Stange auf Schlüsselbein', 'Enger als schulterbreit greifen', 'Kopf zurücknehmen beim Drücken', 'Rumpf anspannen'],
    commonMistakes: ['Ins Hohlkreuz gehen', 'Stange vor dem Kopf drücken', 'Kein Lockout oben'],
    alternatives: ['kurzhantel-schulter-druecken-sitzend', 'arnold-press', 'maschinen-schulter-druecken'],
    pros: ['Höchste Schulterbelastung', 'Compound-Übung', 'Stärkt Core mit'],
    cons: ['Hohe Technik-Anforderung', 'Belastet unteren Rücken', 'Schulterimpingement-Risiko'],
  },
  {
    id: 'kurzhantel-schulter-druecken-sitzend', name: 'Kurzhantel-Schulterdrücken sitzend',
    description: 'Sitzend Kurzhanteln über den Kopf drücken. Freiere Bewegungsbahn als mit Langhantel.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['90° Bankneigung', 'Kurzhanteln auf Schulterhöhe', 'Senkrecht nach oben drücken'],
    commonMistakes: ['Rücken wölbt sich', 'Ellbogen zu weit vorne', 'Gewichte zusammenschlagen'],
    alternatives: ['langhantel-schulter-druecken', 'arnold-press', 'maschinen-schulter-druecken'],
    pros: ['Schulterfreundlicher', 'Gleicht Ungleichgewichte aus', 'Guter ROM'],
    cons: ['Weniger absolute Last', 'Setup schwierig bei schwerem Gewicht', 'Stabilisation anspruchsvoll'],
  },
  {
    id: 'arnold-press', name: 'Arnold Press',
    description: 'Schulterdrücken mit Rotation — benannt nach Arnold Schwarzenegger. Trainiert alle drei Schulterköpfe.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'intermediate',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '6-8', rest: '2 min', rir: 2 }, hypertrophy: { sets: 4, reps: '8-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Start mit Handflächen zum Gesicht', 'Beim Drücken nach außen rotieren', 'Oben Handflächen nach vorne'],
    commonMistakes: ['Zu schnelle Rotation', 'Zu schwer — Technik leidet', 'Kein voller ROM'],
    alternatives: ['kurzhantel-schulter-druecken-sitzend', 'langhantel-schulter-druecken', 'maschinen-schulter-druecken'],
    pros: ['Trainiert alle Schulterköpfe', 'Gute Time-Under-Tension', 'Variation zum Standard-Drücken'],
    cons: ['Weniger Maximallast', 'Schulterbelastung durch Rotation', 'Technik anspruchsvoll'],
  },
  {
    id: 'kurzhantel-seitliches-heben', name: 'Kurzhantel Seitheben',
    description: 'Die wichtigste Isolationsübung für den seitlichen Deltamuskel. Runde, breite Schultern.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['traps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Leicht vorbeugen', 'Daumen leicht nach unten kippen', 'Bis Schulterhöhe heben', 'Kontrolliert senken'],
    commonMistakes: ['Schwungholen aus Hüfte', 'Zu hoch heben (Trap übernimmt)', 'Zu schwer'],
    alternatives: ['kabelzug-seitliches-heben', 'einarmig-kabelzug-lateral', 'maschinen-schulter-druecken'],
    pros: ['Beste Isolation für seitliche Schulter', 'Einfach auszuführen', 'Wenig Equipment'],
    cons: ['Schwer zu steigern', 'Tendenz zum Schwungholen', 'Nur Isolation'],
  },
  {
    id: 'kabelzug-seitliches-heben', name: 'Kabelzug Seitheben',
    description: 'Seitheben am Kabelzug für konstante Spannung über den gesamten Bewegungsumfang.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['traps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Kabel von unten hinter dem Körper', 'Arm leicht gebeugt seitlich heben', 'Bis Schulterhöhe'],
    commonMistakes: ['Zu viel Schwung', 'Trapez übernimmt', 'Falsche Kabelposition'],
    alternatives: ['kurzhantel-seitliches-heben', 'einarmig-kabelzug-lateral', 'band-seitliches-heben'],
    pros: ['Konstante Spannung', 'Bessere Kontraktion', 'Einstellbar'],
    cons: ['Kabelzug nötig', 'Nur ein Arm gleichzeitig', 'Setup-Zeit'],
  },
  {
    id: 'vorgeb-kurzhantel-heben', name: 'Vorgebeugtes Seitheben',
    description: 'Kurzhantel-Seitheben in vorgebeugter Position für den hinteren Deltamuskel.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['back', 'traps'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['90° Vorbeuge', 'Arme seitlich heben', 'Schulterblätter zusammen', 'Ellbogen leicht gebeugt'],
    commonMistakes: ['Nicht genug vorbeugen', 'Schwung aus dem Rücken', 'Zu schwer'],
    alternatives: ['umgekehrtes-fliegen-maschine', 'kabelzug-face-pull', 'vorgeb-kabelzug-heben'],
    pros: ['Wichtig für Schulterbalance', 'Verbessert Haltung', 'Einfaches Setup'],
    cons: ['Unbequeme Position', 'Schwer zu isolieren', 'Unterer Rücken ermüdet'],
  },
  {
    id: 'vorgeb-kabelzug-heben', name: 'Vorgebeugtes Kabelzug-Heben',
    description: 'Vorgebeugtes Seitheben am Kabelzug für konstante Spannung am hinteren Deltamuskel.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['back', 'traps'], difficulty: 'intermediate',
    equipment: ['cable'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Kabel tief einstellen', 'Gekreuzt greifen', 'Vorgebeugt seitlich ziehen'],
    commonMistakes: ['Oberkörper aufrichtet sich', 'Zu viel Trapez', 'Falscher Kabelwinkel'],
    alternatives: ['vorgeb-kurzhantel-heben', 'kabelzug-face-pull', 'umgekehrtes-fliegen-maschine'],
    pros: ['Konstante Spannung', 'Gute Kontraktion', 'Schulterfreundlich'],
    cons: ['Kabelzug nötig', 'Technik erfordert Übung', 'Setup aufwändig'],
  },
  {
    id: 'kurzhantel-frontheben', name: 'Kurzhantel-Frontheben',
    description: 'Kurzhanteln nach vorne heben für den vorderen Deltamuskel.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['chest'], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Arme leicht gebeugt', 'Bis Schulterhöhe heben', 'Kontrolliert senken'],
    commonMistakes: ['Zu hoch heben', 'Schwungholen', 'Zu schwer'],
    alternatives: ['kabelzug-frontheben', 'plates-frontheben', 'langhantel-schulter-druecken'],
    pros: ['Einfach auszuführen', 'Isoliert vorderen Deltoid', 'Wenig Equipment'],
    cons: ['Vorderer Deltoid oft schon überlastet', 'Schwer zu steigern', 'Nur Isolation'],
  },
  {
    id: 'kabelzug-frontheben', name: 'Kabelzug-Frontheben',
    description: 'Frontheben am Kabelzug für konstante Spannung und bessere Kontraktion.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['chest'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Kabel von unten', 'Arm gestreckt nach vorne heben', 'Bis Schulterhöhe'],
    commonMistakes: ['Lehnt sich zurück', 'Zu viel Schwung', 'Trapez übernimmt'],
    alternatives: ['kurzhantel-frontheben', 'plates-frontheben', 'arnold-press'],
    pros: ['Konstante Spannung', 'Gut für Nachermüdung', 'Einstellbar'],
    cons: ['Kabelzug nötig', 'Nur Isolation', 'Vorderer Deltoid oft genug trainiert'],
  },
  {
    id: 'maschinen-schulter-druecken', name: 'Maschinen-Schulterdrücken',
    description: 'Geführtes Schulterdrücken an der Maschine. Sicher und anfängerfreundlich.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '6-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Sitzhöhe einstellen', 'Griffe auf Schulterhöhe', 'Senkrecht nach oben drücken'],
    commonMistakes: ['Falsche Sitzhöhe', 'Nicht voll durchstrecken', 'Rücken wölbt sich'],
    alternatives: ['kurzhantel-schulter-druecken-sitzend', 'langhantel-schulter-druecken', 'smith-schulter-druecken'],
    pros: ['Sicher ohne Spotter', 'Leicht zu erlernen', 'Gut für Nachermüdung'],
    cons: ['Weniger Stabilisatorenarbeit', 'Fester Bewegungsweg', 'Maschinenabhängig'],
  },
  {
    id: 'einarmig-kurzhantel-schulter-druecken', name: 'Einarmiges Kurzhantel-Schulterdrücken',
    description: 'Unilaterales Schulterdrücken für Core-Stabilität und Ausgleich von Kraftunterschieden.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps', 'core'], difficulty: 'intermediate',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '5-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Stehend oder sitzend', 'Core maximal anspannen', 'Senkrecht nach oben drücken'],
    commonMistakes: ['Seitlich wegkippen', 'Core nicht anspannen', 'Schulter hochziehen'],
    alternatives: ['kurzhantel-schulter-druecken-sitzend', 'arnold-press', 'langhantel-schulter-druecken'],
    pros: ['Extreme Core-Anforderung', 'Behebt Dysbalancen', 'Funktionelle Kraft'],
    cons: ['Weniger absolute Last', 'Doppelte Trainingszeit', 'Schwierig zu stabilisieren'],
  },
  {
    id: 'kurzhantel-upright-row', name: 'Kurzhantel Aufrechtes Rudern',
    description: 'Kurzhanteln eng am Körper nach oben ziehen. Trainiert seitliche Schulter und Trapez.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['traps', 'biceps'], difficulty: 'intermediate',
    equipment: ['dumbbell'], injuriesToAvoid: ['shoulder', 'wrist'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '6-8', rest: '2 min', rir: 2 }, hypertrophy: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Kurzhanteln nah am Körper führen', 'Ellbogen über Handgelenke heben', 'Bis Brusthöhe'],
    commonMistakes: ['Zu hoch ziehen — Impingement-Risiko', 'Schwungholen', 'Handgelenke knicken ab'],
    alternatives: ['kurzhantel-seitliches-heben', 'kabelzug-seitliches-heben', 'langhantel-schulter-druecken'],
    pros: ['Trainiert Schulter und Trap', 'Kompakte Bewegung', 'Gute Alternative zum Seitheben'],
    cons: ['Impingement-Risiko', 'Belastet Handgelenke', 'Umstritten in der Trainingsszene'],
  },
  {
    id: 'einarmig-kabelzug-lateral', name: 'Einarmiges Kabelzug-Seitheben',
    description: 'Unilaterales Seitheben am Kabelzug für maximale seitliche Schulteraktivierung.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['traps'], difficulty: 'beginner',
    equipment: ['cable'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Kabel hinter dem Körper führen', 'Arm leicht gebeugt seitlich heben', 'Kontrolliert zurück'],
    commonMistakes: ['Körper lehnt sich weg', 'Trapez übernimmt', 'Zu schnell'],
    alternatives: ['kabelzug-seitliches-heben', 'kurzhantel-seitliches-heben', 'band-seitliches-heben'],
    pros: ['Maximale Kontraktion', 'Behebt Ungleichgewichte', 'Konstante Spannung'],
    cons: ['Kabelzug nötig', 'Doppelte Zeit', 'Wenig Last'],
  },
  {
    id: 'landmine-schulter-druecken', name: 'Landmine-Schulterdrücken',
    description: 'Schulterdrücken an der Landmine für einen einzigartigen, schulterfreundlichen Druckwinkel.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps', 'core'], difficulty: 'intermediate',
    equipment: ['barbell'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '2 min', rir: 1 }, hypertrophy: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 3, reps: '8-12', rest: '75 sec', rir: 2 },
    },
    formCues: ['Stange mit einer Hand am Ende greifen', 'Schräg nach oben drücken', 'Andere Hand stützt ab'],
    commonMistakes: ['Zu weit vom Drehpunkt', 'Rücken wölbt sich', 'Kein stabiler Stand'],
    alternatives: ['kurzhantel-schulter-druecken-sitzend', 'arnold-press', 'maschinen-schulter-druecken'],
    pros: ['Sehr schulterfreundlich', 'Einzigartiger Winkel', 'Core-Training inklusive'],
    cons: ['Landmine-Halterung nötig', 'Ungewöhnlich', 'Weniger Standardisiert'],
  },
  {
    id: 'aussenrotation-kurzhantel', name: 'Außenrotation mit Kurzhantel',
    description: 'Seitlich liegend die Kurzhantel nach außen rotieren. Essentiell für Schultergesundheit.',
    primaryMuscle: 'shoulders', secondaryMuscles: [], difficulty: 'beginner',
    equipment: ['dumbbell'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '12-15', rest: '60 sec', rir: 3 }, hypertrophy: { sets: 3, reps: '15-20', rest: '45 sec', rir: 3 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 3 }, recomp: { sets: 3, reps: '15-20', rest: '45 sec', rir: 3 },
    },
    formCues: ['Seitlich liegen', 'Ellbogen am Körper fixieren', 'Langsam nach außen rotieren'],
    commonMistakes: ['Zu schwer', 'Ellbogen bewegt sich', 'Zu schnell'],
    alternatives: ['band-schulter-rotation', 'kabelzug-face-pull', 'vorgeb-kurzhantel-heben'],
    pros: ['Essentiell für Schultergesundheit', 'Präventiv', 'Überall ausführbar'],
    cons: ['Langweilig', 'Kein Hypertrophie-Effekt', 'Sehr leichtes Gewicht'],
  },
  {
    id: 'band-schulter-rotation', name: 'Band-Außenrotation',
    description: 'Außenrotation mit Widerstandsband. Ideal als Aufwärmübung vor dem Schultertraining.',
    primaryMuscle: 'shoulders', secondaryMuscles: [], difficulty: 'beginner',
    equipment: ['bands'], injuriesToAvoid: [],
    recommendedSetsReps: {
      strength: { sets: 2, reps: '15-20', rest: '30 sec', rir: 3 }, hypertrophy: { sets: 2, reps: '15-20', rest: '30 sec', rir: 3 },
      definition: { sets: 2, reps: '15-20', rest: '30 sec', rir: 3 }, recomp: { sets: 2, reps: '15-20', rest: '30 sec', rir: 3 },
    },
    formCues: ['Band an Türknauf oder Rack', 'Ellbogen 90° gebeugt fixiert', 'Nach außen rotieren'],
    commonMistakes: ['Zu starkes Band', 'Ellbogen bewegt sich', 'Zu schnell'],
    alternatives: ['aussenrotation-kurzhantel', 'kabelzug-face-pull', 'vorgeb-kurzhantel-heben'],
    pros: ['Perfekt zum Aufwärmen', 'Tragbar', 'Sehr schulterfreundlich'],
    cons: ['Kein Muskelaufbau', 'Nur Aufwärmen', 'Band kann reißen'],
  },
  {
    id: 'plates-frontheben', name: 'Hantelscheibe Frontheben',
    description: 'Frontheben mit einer Gewichtsscheibe. Natürlicher Griff und gute Kontraktion.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['chest', 'core'], difficulty: 'beginner',
    equipment: ['barbell'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 3, reps: '8-10', rest: '90 sec', rir: 2 }, hypertrophy: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      definition: { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 }, recomp: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: ['Scheibe seitlich greifen', 'Arme gestreckt nach vorne heben', 'Bis Augenhöhe'],
    commonMistakes: ['Schwungholen', 'Zurücklehnen', 'Zu schwere Scheibe'],
    alternatives: ['kurzhantel-frontheben', 'kabelzug-frontheben', 'langhantel-schulter-druecken'],
    pros: ['Natürlicher Griff', 'Gute Core-Arbeit', 'Überall verfügbar'],
    cons: ['Begrenzte Last', 'Nur Isolation', 'Gewichtsstufen limitiert'],
  },
  {
    id: 'smith-schulter-druecken', name: 'Smith-Maschinen-Schulterdrücken',
    description: 'Geführtes Schulterdrücken an der Smith-Maschine. Ermöglicht schwere Lasten ohne Spotter.',
    primaryMuscle: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'beginner',
    equipment: ['machine'], injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength: { sets: 4, reps: '5-8', rest: '3 min', rir: 1 }, hypertrophy: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
      definition: { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 }, recomp: { sets: 4, reps: '8-12', rest: '90 sec', rir: 2 },
    },
    formCues: ['Bank leicht nach hinten neigen', 'Unter der Stange positionieren', 'Senkrecht drücken'],
    commonMistakes: ['Falsche Position unter der Stange', 'Zu weit vorne/hinten', 'Rücken überstreckt'],
    alternatives: ['langhantel-schulter-druecken', 'maschinen-schulter-druecken', 'kurzhantel-schulter-druecken-sitzend'],
    pros: ['Sicher', 'Schwere Lasten möglich', 'Kein Spotter nötig'],
    cons: ['Fester Bewegungsweg', 'Weniger Stabilisatoren', 'Kann Schultern belasten'],
  },
];
