import type { Exercise } from '@/types';

export const EXERCISES: Exercise[] = [
  // ─── CHEST ───────────────────────────────────────────────────────
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    description: 'The king of chest exercises. Lie flat on a bench, grip the barbell slightly wider than shoulder-width, and press explosively while maintaining a tight arch and retracted scapula.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '3-5',   rest: '3-5 min', rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12',  rest: '90 sec',  rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec',  rir: 2 },
      recomp:      { sets: 4, reps: '8-10',  rest: '90 sec',  rir: 2 },
    },
    formCues: [
      'Retract and depress your scapula before unracking',
      'Keep your feet flat on the floor for a stable base',
      'Touch the bar to your lower chest, not your neck',
      'Drive your feet into the floor as you press',
      'Keep wrists straight and directly over elbows',
    ],
    commonMistakes: [
      'Flaring elbows out 90° — keep at 45–75° to protect shoulders',
      'Bouncing the bar off the chest — control the eccentric',
      'Losing upper back tightness — stay retracted throughout',
    ],
    alternatives: ['dumbbell-bench-press', 'incline-dumbbell-press', 'push-up', 'cable-chest-fly'],
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    description: 'Greater range of motion than barbell. Allows each arm to move independently, reducing strength imbalances and being safer for the shoulder joint.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['shoulder', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Start with dumbbells at chest level, elbows at 45°',
      'Press up and in — dumbbells should nearly touch at the top',
      'Control the descent over 2-3 seconds',
      'Neutral or semi-pronated grip to reduce shoulder stress',
    ],
    commonMistakes: [
      'Going too heavy and losing range of motion',
      'Not touching dumbbells at the top — you lose the peak contraction',
    ],
    alternatives: ['barbell-bench-press', 'push-up', 'cable-chest-fly', 'machine-chest-press'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    description: 'Targets the upper clavicular head of the pectoralis major. Bench set to 30–45°. Essential for a full, developed chest.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    difficulty: 'intermediate',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Set bench to exactly 30-45° — higher angles shift stress to shoulders',
      'Lower the dumbbells to upper chest level',
      'Keep elbows at 45° to your torso',
      'Squeeze at the top without locking out hard',
    ],
    commonMistakes: [
      'Too steep an incline — becomes a shoulder press',
      'Not getting full depth at the bottom',
    ],
    alternatives: ['incline-barbell-press', 'cable-chest-fly', 'push-up'],
  },
  {
    id: 'cable-chest-fly',
    name: 'Cable Chest Fly',
    description: 'Isolates the chest through a full arc of motion with constant cable tension. Excellent finisher for chest hypertrophy.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Slight forward lean — think hugging a barrel',
      'Maintain a slight bend in the elbow throughout',
      'Bring hands together and squeeze hard at the peak',
      'Control the return — full stretch at the bottom',
    ],
    commonMistakes: [
      'Bending the elbows too much — turns into a press',
      'Not using the full range of motion',
    ],
    alternatives: ['dumbbell-fly', 'pec-deck', 'push-up'],
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    description: 'Classic bodyweight chest exercise. Scalable from beginner to advanced with foot elevation and weighted vests.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['wrist'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '15-20',   rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '20-25',   rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '20-30',   rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '15-20',   rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Hands slightly wider than shoulder-width',
      'Keep body in a straight line — no sagging hips',
      'Touch chest to the floor on each rep',
      'Protract scapula fully at the top',
    ],
    commonMistakes: [
      'Sagging hips — weakens the movement and stresses lower back',
      'Flaring elbows out — keep at 45°',
    ],
    alternatives: ['dumbbell-bench-press', 'barbell-bench-press', 'cable-chest-fly'],
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    description: 'Fixed-path chest press ideal for beginners or as a finishing movement. Allows focus on chest contraction without stabilisation demands.',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    difficulty: 'beginner',
    equipment: ['machine'],
    injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '2 min',  rir: 2 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Adjust seat so handles are at mid-chest height',
      'Keep lower back pressed against the pad',
      'Do not lock out elbows at full extension',
    ],
    commonMistakes: [
      'Seat too high — becomes a shoulder press',
      'Bouncing the weight stack',
    ],
    alternatives: ['barbell-bench-press', 'dumbbell-bench-press', 'push-up'],
  },

  // ─── BACK ────────────────────────────────────────────────────────
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    description: 'Premier back thickness builder. Hinge forward at 45°, pull the bar to your lower sternum keeping elbows at 45° to the torso.',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'traps', 'lats'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '3-5',   rest: '3-5 min', rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12',  rest: '90 sec',  rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec',  rir: 2 },
      recomp:      { sets: 4, reps: '8-10',  rest: '90 sec',  rir: 2 },
    },
    formCues: [
      'Hip hinge to 45°, bar directly under your shoulder blades',
      'Row to your lower sternum, NOT your belly button',
      'Squeeze shoulder blades together at the top',
      'Keep your neck neutral — look at the floor 2m ahead',
    ],
    commonMistakes: [
      'Jerking with the lower back — keep it rigid',
      'Rowing too high or too low',
      'Rounding the upper back during the pull',
    ],
    alternatives: ['dumbbell-row', 'cable-row', 'machine-row', 'lat-pulldown'],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    description: 'The ultimate bodyweight back exercise. Full scapular retraction and depression with controlled tempo builds elite lat width and strength.',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps', 'back', 'traps'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '3-6',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '6-10',  rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '8-12',  rest: '60 sec', rir: 2 },
      recomp:      { sets: 4, reps: '6-8',   rest: '90 sec', rir: 2 },
    },
    formCues: [
      'Start from a dead hang — full arm extension',
      'Depress and retract scapula before pulling',
      'Drive elbows toward your hips — not just pull with arms',
      'Chin clears the bar — controlled 3-second descent',
    ],
    commonMistakes: [
      'Kipping — reduces muscle activation',
      'Not achieving full lockout at the bottom',
      'Using too much bicep, not enough lat',
    ],
    alternatives: ['lat-pulldown', 'assisted-pull-up', 'cable-row', 'barbell-row'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    description: 'Machine version of the pull-up. Allows easy load manipulation. Use a wide overhand grip, lean back slightly, pull to upper chest.',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps', 'back'],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['shoulder', 'elbow'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '2 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: ['12-15'].join(''), rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Lean back 15-20° — not vertical, not 45°',
      'Pull bar to upper chest / clavicle',
      'Lead with your elbows, think of them as hooks',
      'Squeeze lats hard at the bottom',
    ],
    commonMistakes: [
      'Pulling to the back of the neck — shoulder injury risk',
      'Leaning too far back — turns into a row',
    ],
    alternatives: ['pull-up', 'cable-row', 'dumbbell-row'],
  },
  {
    id: 'dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    description: 'Excellent unilateral back exercise. Plant knee on bench, row dumbbell to hip with full scapular retraction.',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'lats'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['lower-back', 'shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '2 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Support with opposite hand and same-side knee on bench',
      'Row to your hip, not your shoulder',
      'Rotate torso slightly at the top for full contraction',
      'Keep the non-working shoulder packed down',
    ],
    commonMistakes: [
      'Twisting the whole body to lift more weight',
      'Not achieving full range of motion',
    ],
    alternatives: ['barbell-row', 'cable-row', 'lat-pulldown'],
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    description: 'Constant tension cable row targeting mid-back thickness. Use a neutral grip handle for maximum lat engagement.',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'lats', 'traps'],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['lower-back'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '2 min',  rir: 2 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Sit tall — do not round your lower back',
      'Initiate the pull by retracting your shoulder blades first',
      'Drive elbows past your torso and squeeze hard',
      'Control the return — stretch the lats fully',
    ],
    commonMistakes: [
      'Using momentum by rocking back and forth',
      'Not getting the full stretch at the front',
    ],
    alternatives: ['barbell-row', 'dumbbell-row', 'machine-row'],
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    description: 'The ultimate full-body exercise. Pulls weight from the floor with a hip-hinge pattern. Unmatched for total back, glute and hamstring development.',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes', 'hamstrings', 'quads', 'traps', 'core'],
    difficulty: 'advanced',
    equipment: ['barbell'],
    injuriesToAvoid: ['lower-back', 'hip'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '1-5',  rest: '5 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '5-8',  rest: '3 min',  rir: 2 },
      definition:  { sets: 3, reps: '8-10', rest: '2 min',  rir: 2 },
      recomp:      { sets: 4, reps: '5-6',  rest: '3 min',  rir: 1 },
    },
    formCues: [
      'Bar over mid-foot — about 1 inch from your shins',
      'Hip hinge to grip: hips higher than knees, shoulders above hips',
      'Take the slack out of the bar before pulling',
      'Push the floor away — leg drive, not just pulling',
      'Lock out by driving hips forward, not leaning back',
    ],
    commonMistakes: [
      'Rounding the lower back — most common injury cause',
      'Bar drifting away from the body — increases lever arm',
      'Jerking the weight off the floor — always pull the slack first',
    ],
    alternatives: ['romanian-deadlift', 'trap-bar-deadlift', 'cable-row'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    description: 'Hip-hinge movement targeting hamstrings and glutes. Start standing, hinge at hips keeping bar close to legs, stop when you feel a deep hamstring stretch.',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back', 'lats'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['lower-back', 'hamstring'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12',  rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Soft bend in knees — this is a hip hinge not a squat',
      'Bar drags down your legs the whole time',
      'Push hips back as far as possible before lowering',
      'Feel the stretch in hamstrings, then drive hips forward',
    ],
    commonMistakes: [
      'Going too low — lose neutral spine',
      'Bending knees too much — turns into a squat',
    ],
    alternatives: ['deadlift', 'good-morning', 'leg-curl'],
  },

  // ─── SHOULDERS ───────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    description: 'The king of shoulder exercises. Press a barbell from upper chest to full overhead extension. Requires full body tension and core stability.',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'traps', 'core'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff', 'lower-back', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '3-5',   rest: '4 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '8-10',  rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
      recomp:      { sets: 4, reps: '6-10',  rest: '2 min',  rir: 2 },
    },
    formCues: [
      'Grip slightly wider than shoulder width',
      'Tuck chin as bar passes — avoid behind-the-neck path',
      'Squeeze glutes and brace core throughout',
      'Bar path is vertical — slightly back over heels at lockout',
    ],
    commonMistakes: [
      'Excessive lower back arch — use lighter weight',
      'Press path too far forward — bar should go straight up',
    ],
    alternatives: ['dumbbell-shoulder-press', 'machine-shoulder-press', 'arnold-press'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    description: 'Seated or standing dumbbell press for shoulder development. Greater range of motion and individual arm loading vs. barbell.',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'traps'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Start with dumbbells at ear height, elbows at 90°',
      'Press up and in — slight arc toward center',
      'Do not lock out hard — keep tension on delts',
    ],
    commonMistakes: [
      'Too wide a starting position — puts rotator cuff at risk',
      'Leaning too far back — becomes incline press',
    ],
    alternatives: ['overhead-press', 'arnold-press', 'lateral-raise'],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    description: 'Isolation exercise for the medial deltoid — the muscle responsible for shoulder width. Use moderate weight with strict form.',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps'],
    difficulty: 'beginner',
    equipment: ['dumbbell', 'cable'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '15-20', rest: '45 sec', rir: 2 },
      definition:  { sets: 4, reps: '15-25', rest: '30 sec', rir: 2 },
      recomp:      { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Slight forward lean — 10-15° torso tilt',
      'Lead with the elbow, not the wrist',
      'Pinky slightly higher than thumb at the top',
      'Stop at shoulder height — above = traps take over',
    ],
    commonMistakes: [
      'Using momentum to swing the weight up',
      'Going too heavy — ruins technique',
    ],
    alternatives: ['cable-lateral-raise', 'machine-lateral-raise'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    description: 'Cable exercise targeting rear deltoids and external rotators. Critical for shoulder health and posture. Pull rope to face level with hands by ears.',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '15-20', rest: '45 sec', rir: 2 },
      definition:  { sets: 3, reps: '20-25', rest: '30 sec', rir: 2 },
      recomp:      { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Set cable at or above head height',
      'Pull rope handles to either side of your face',
      'Externally rotate — thumbs point behind you at peak',
      'Control the return fully',
    ],
    commonMistakes: [
      'Pulling to neck instead of face',
      'Not externally rotating at peak — misses the rear delt',
    ],
    alternatives: ['rear-delt-fly', 'band-pull-apart'],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    description: 'Isolation exercise for the posterior deltoid. Hinge forward, raise dumbbells out to sides with a slight bend in the elbow.',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '12-20', rest: '45 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '30 sec', rir: 2 },
      recomp:      { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Hinge forward at hips until torso is nearly parallel to floor',
      'Arms hang directly below shoulders',
      'Arc dumbbells out and up to shoulder height',
      'Squeeze rear delts at the top',
    ],
    commonMistakes: [
      'Not hinging forward enough — works mid-traps instead',
      'Too much elbow bend — involves biceps',
    ],
    alternatives: ['face-pull', 'cable-lateral-raise', 'machine-rear-delt'],
  },

  // ─── LEGS ────────────────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    description: 'The premier lower body exercise. Bar on upper traps, descend to parallel or below with knees tracking over toes.',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core', 'back'],
    difficulty: 'advanced',
    equipment: ['barbell'],
    injuriesToAvoid: ['knee', 'lower-back', 'hip'],
    recommendedSetsReps: {
      strength:    { sets: 5, reps: '3-5',  rest: '5 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '6-10', rest: '3 min',  rir: 2 },
      definition:  { sets: 3, reps: '10-15',rest: '90 sec', rir: 2 },
      recomp:      { sets: 4, reps: '6-8',  rest: '3 min',  rir: 2 },
    },
    formCues: [
      'High bar: more upright torso. Low bar: more forward lean.',
      'Brace core like you are about to take a punch',
      'Knees track over pinky toe — no caving in',
      'Drive through the whole foot, especially heels',
      'Descend until hips are below knees',
    ],
    commonMistakes: [
      'Knees caving inward (valgus collapse)',
      'Heels rising — work on ankle mobility',
      'Not hitting depth',
    ],
    alternatives: ['goblet-squat', 'leg-press', 'hack-squat', 'bulgarian-split-squat'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    description: 'Machine-based quad and glute exercise. Allows heavy loading with reduced spinal compression. Feet placement varies muscle emphasis.',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    difficulty: 'beginner',
    equipment: ['machine'],
    injuriesToAvoid: ['knee', 'lower-back'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '2 min',  rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '90 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-15', rest: '2 min',  rir: 2 },
    },
    formCues: [
      'Feet shoulder-width apart, toes slightly out',
      'Lower until knees are at 90° or less',
      'Do not lock out knees at top — maintain tension',
      'Higher foot placement targets glutes/hamstrings',
    ],
    commonMistakes: [
      'Locking out knees — knee injury risk',
      'Letting the lower back peel off the pad',
    ],
    alternatives: ['barbell-squat', 'hack-squat', 'goblet-squat'],
  },
  {
    id: 'romanian-deadlift-db',
    name: 'Dumbbell Romanian Deadlift',
    description: 'Dumbbell version of the RDL. Greater range of motion than barbell version and kinder to the lower back.',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['lower-back', 'hamstring'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '2 min',  rir: 2 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Dumbbells start at hip height',
      'Hip hinge — push hips back as you lower',
      'Dumbbells track down the front of your legs',
      'Feel the deep hamstring stretch before returning',
    ],
    commonMistakes: [
      'Rounding the back',
      'Squatting instead of hinging',
    ],
    alternatives: ['romanian-deadlift', 'leg-curl', 'good-morning'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    description: 'Single-leg squat with rear foot elevated. Brutal quad and glute developer with excellent carryover to athletic performance.',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    difficulty: 'intermediate',
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    injuriesToAvoid: ['knee', 'hip', 'ankle'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '5-6',  rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12', rest: '2 min',  rir: 2 },
      definition:  { sets: 3, reps: '12-15',rest: '90 sec', rir: 2 },
      recomp:      { sets: 3, reps: '8-12', rest: '2 min',  rir: 2 },
    },
    formCues: [
      'Front foot far enough forward that shin stays vertical',
      'Rear foot on bench — top of foot or ball of foot',
      'Descend straight down — do not lunge forward',
      'Drive through front heel to stand',
    ],
    commonMistakes: [
      'Front foot too close — heel rises, knee extends past toe',
      'Leaning too far forward',
    ],
    alternatives: ['barbell-squat', 'leg-press', 'walking-lunge'],
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    description: 'Machine isolation exercise for the hamstrings. Essential for balanced leg development.',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['calves'],
    difficulty: 'beginner',
    equipment: ['machine'],
    injuriesToAvoid: ['knee', 'hamstring'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Pad just above the Achilles heel',
      'Hips pressed firmly into the pad',
      'Full range: stretch at bottom, squeeze at top',
      'Do not let hips rise off the pad',
    ],
    commonMistakes: [
      'Using too much weight and losing full range',
      'Hips rising — reduces hamstring isolation',
    ],
    alternatives: ['romanian-deadlift', 'nordic-curl', 'cable-leg-curl'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    description: 'Dumbbell or kettlebell held at chest, squat to depth. Great for beginners and as a warm-up movement. Naturally promotes upright torso.',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    difficulty: 'beginner',
    equipment: ['dumbbell', 'kettlebell'],
    injuriesToAvoid: ['knee'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '10-12', rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '12-15', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Hold dumbbell vertically at chest',
      'Elbows inside knees at the bottom — use them to push knees out',
      'Sit into the squat — full depth',
    ],
    commonMistakes: [
      'Not reaching depth',
      'Allowing knees to collapse inward',
    ],
    alternatives: ['barbell-squat', 'leg-press', 'bodyweight-squat'],
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    description: 'The premier glute exercise. Barbell across hips, upper back on bench, drive hips to full extension through glute contraction.',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['lower-back', 'hip'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Upper back on bench at mid-scapula',
      'Chin tucked throughout — do not extend neck at top',
      'Drive through heels — not toes',
      'Squeeze glutes hard at full extension',
    ],
    commonMistakes: [
      'Hyperextending the lower back at the top',
      'Feet too close or too far — thighs should be parallel at top',
    ],
    alternatives: ['glute-bridge', 'cable-kickback', 'single-leg-hip-thrust'],
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    description: 'Standing calf raises for gastrocnemius development. Full range: deep stretch at bottom, full contraction at top.',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: ['machine', 'bodyweight', 'dumbbell'],
    injuriesToAvoid: ['ankle'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '8-10',  rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 5, reps: '10-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 4, reps: '15-25', rest: '30 sec', rir: 2 },
      recomp:      { sets: 4, reps: '12-20', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Full stretch at the bottom — 2-second pause',
      'Rise onto the ball of your foot, not toes',
      'Hold contraction at the top for 1 second',
      'Slow, controlled descent',
    ],
    commonMistakes: [
      'Partial range of motion — calves respond to full stretch',
      'Too fast — momentum reduces time under tension',
    ],
    alternatives: ['seated-calf-raise', 'leg-press-calf-raise'],
  },

  // ─── ARMS ────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Bicep Curl',
    description: 'Classic bicep exercise. Stand with supinated grip, curl bar to full contraction while keeping elbows pinned at sides.',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['arms'],
    difficulty: 'beginner',
    equipment: ['barbell'],
    injuriesToAvoid: ['elbow', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '2 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
    },
    formCues: [
      'Elbows pinned at sides — do not let them travel forward',
      'Supinate fully at the top for peak bicep contraction',
      'Lower the bar fully — full extension is important',
      'No swinging — isolate the bicep',
    ],
    commonMistakes: [
      'Swinging body to lift more weight',
      'Elbows drifting forward — reduces bicep tension',
    ],
    alternatives: ['dumbbell-curl', 'incline-dumbbell-curl', 'hammer-curl', 'cable-curl'],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Bicep Curl',
    description: 'Alternating or simultaneous dumbbell curls. Supinate wrist as you curl to maximise bicep contraction.',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['arms'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['elbow', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-8',   rest: '2 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-12', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Start with neutral grip (hammer), rotate to supinated as you curl',
      'Elbow stays at side — do not swing',
      'Slow 2-3 second descent',
    ],
    commonMistakes: [
      'Not supinating — misses the short head peak',
      'Going too heavy and using momentum',
    ],
    alternatives: ['barbell-curl', 'cable-curl', 'hammer-curl'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    description: 'Neutral grip curl targeting the brachialis and brachioradialis for arm thickness. Often underutilised.',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['arms'],
    difficulty: 'beginner',
    equipment: ['dumbbell'],
    injuriesToAvoid: ['elbow'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '8-10',  rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-12', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Maintain neutral (thumbs up) grip throughout',
      'Elbows at sides, curl to shoulder level',
      'Controlled descent',
    ],
    commonMistakes: [
      'Rotating the wrist — defeats the purpose',
    ],
    alternatives: ['barbell-curl', 'dumbbell-curl', 'cable-curl'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    description: 'Barbell bench press with a shoulder-width grip to maximally load the triceps. One of the best mass builders for the triceps.',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    difficulty: 'intermediate',
    equipment: ['barbell'],
    injuriesToAvoid: ['elbow', 'wrist', 'shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '5-8',   rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12',  rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 4, reps: '8-12',  rest: '90 sec', rir: 2 },
    },
    formCues: [
      'Shoulder-width grip — not too narrow (puts stress on wrists)',
      'Tuck elbows close to torso throughout',
      'Lower bar to lower chest',
      'Drive up explosively',
    ],
    commonMistakes: [
      'Grip too narrow — causes wrist pain',
      'Elbows flaring — loses tricep focus',
    ],
    alternatives: ['tricep-pushdown', 'overhead-tricep-extension', 'dips'],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Cable Pushdown',
    description: 'Cable isolation for the triceps. Use rope or bar attachment. Keep elbows pinned at sides throughout the movement.',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['elbow'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Elbows pinned at sides — do not let them drift back',
      'Full extension at the bottom — squeeze triceps hard',
      'Controlled return to start position',
      'Rope: spread handles apart at the bottom for extra contraction',
    ],
    commonMistakes: [
      'Letting elbows travel back — turns into a lat exercise',
      'Not achieving full extension',
    ],
    alternatives: ['overhead-tricep-extension', 'close-grip-bench', 'dips'],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    description: 'Dumbbell or cable overhead extension for the long head of the triceps. The overhead position creates a deep stretch for maximum hypertrophy.',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: ['dumbbell', 'cable'],
    injuriesToAvoid: ['elbow', 'shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Keep elbows pointing straight forward — not flaring out',
      'Lower slowly — feel the stretch in the long head',
      'Extend to full lockout above your head',
    ],
    commonMistakes: [
      'Elbows flaring — reduces tricep isolation and stresses elbow',
    ],
    alternatives: ['tricep-pushdown', 'close-grip-bench', 'skull-crusher'],
  },
  {
    id: 'dips',
    name: 'Parallel Bar Dips',
    description: 'Bodyweight compound exercise for triceps and lower chest. Lean forward slightly for chest emphasis, stay upright for triceps.',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['shoulder', 'rotator-cuff', 'elbow'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '6-10',  rest: '3 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-20', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-15', rest: '90 sec', rir: 2 },
    },
    formCues: [
      'Full depth: upper arm parallel to floor or lower',
      'Keep shoulders packed down — no shrugging',
      'Slight forward lean for chest bias',
    ],
    commonMistakes: [
      'Not going deep enough',
      'Shrugging shoulders — impingement risk',
    ],
    alternatives: ['close-grip-bench', 'tricep-pushdown', 'machine-dip'],
  },

  // ─── CORE ────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    description: 'Isometric core stability exercise. Maintain a rigid straight-line position from head to heels.',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders', 'glutes'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['lower-back', 'shoulder', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '30-60s', rest: '60 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '45-60s', rest: '45 sec', rir: 2 },
      definition:  { sets: 3, reps: '60-90s', rest: '30 sec', rir: 2 },
      recomp:      { sets: 3, reps: '45-60s', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Forearms or hands directly below shoulders',
      'Squeeze glutes and core — no sagging hips',
      'Neutral neck — look at the floor',
      'Breathe steadily throughout',
    ],
    commonMistakes: [
      'Hips sagging or raised too high',
      'Holding breath',
    ],
    alternatives: ['hollow-hold', 'ab-wheel-rollout', 'dead-bug'],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    description: 'Weighted abdominal crunch using cable resistance. Kneel facing cable stack, pull weight by flexing the spine (crunching).',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: ['cable'],
    injuriesToAvoid: ['lower-back', 'neck'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '10-12', rest: '75 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '12-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '15-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '12-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Kneel and hold rope beside your ears — do not pull with arms',
      'Round your spine — think elbow to knee',
      'Full contraction at the bottom, slow return',
    ],
    commonMistakes: [
      'Pulling with the arms instead of flexing the spine',
      'Partial range of motion',
    ],
    alternatives: ['hanging-leg-raise', 'ab-wheel-rollout', 'plank'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    description: 'Advanced core exercise requiring grip strength. Hang from a bar and raise straight legs to 90° or higher. Targets lower abs.',
    primaryMuscle: 'core',
    secondaryMuscles: ['lats', 'arms'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['lower-back', 'shoulder'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '8-12',  rest: '90 sec', rir: 2 },
      hypertrophy: { sets: 4, reps: '10-15', rest: '60 sec', rir: 2 },
      definition:  { sets: 3, reps: '12-20', rest: '45 sec', rir: 2 },
      recomp:      { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 },
    },
    formCues: [
      'Do not swing — controlled movement throughout',
      'Posteriorly tilt pelvis to engage lower abs',
      'Raise legs until parallel to floor minimum',
      'Slow 3-second descent',
    ],
    commonMistakes: [
      'Swinging and using momentum',
      'Not tilting the pelvis — uses hip flexors only',
    ],
    alternatives: ['cable-crunch', 'reverse-crunch', 'plank'],
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    description: 'Advanced anti-extension core exercise. Roll the wheel out as far as possible while maintaining a rigid neutral spine.',
    primaryMuscle: 'core',
    secondaryMuscles: ['lats', 'shoulders'],
    difficulty: 'advanced',
    equipment: ['bodyweight'],
    injuriesToAvoid: ['lower-back', 'shoulder', 'wrist'],
    recommendedSetsReps: {
      strength:    { sets: 3, reps: '5-10',  rest: '2 min',  rir: 1 },
      hypertrophy: { sets: 4, reps: '8-12',  rest: '90 sec', rir: 2 },
      definition:  { sets: 3, reps: '10-15', rest: '60 sec', rir: 2 },
      recomp:      { sets: 3, reps: '8-12',  rest: '90 sec', rir: 2 },
    },
    formCues: [
      'Tuck pelvis before you roll out — do not let lower back arch',
      'Roll as far as you can while maintaining a rigid trunk',
      'Drag yourself back using lats and core',
    ],
    commonMistakes: [
      'Arching lower back — serious injury risk',
      'Going too far too soon — progress gradually',
    ],
    alternatives: ['plank', 'cable-crunch', 'hollow-hold'],
  },

  // ─── CALVES ──────────────────────────────────────────────────────
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    description: 'Seated position targets the soleus muscle more than the gastrocnemius. Essential for complete calf development.',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: ['machine'],
    injuriesToAvoid: ['ankle'],
    recommendedSetsReps: {
      strength:    { sets: 4, reps: '10-12', rest: '75 sec', rir: 2 },
      hypertrophy: { sets: 5, reps: '12-20', rest: '45 sec', rir: 2 },
      definition:  { sets: 4, reps: '15-25', rest: '30 sec', rir: 2 },
      recomp:      { sets: 4, reps: '15-20', rest: '45 sec', rir: 2 },
    },
    formCues: [
      'Knees bent at 90°',
      'Full stretch at the bottom — 2-second pause',
      'Raise as high as possible on ball of foot',
    ],
    commonMistakes: [
      'Using partial range of motion',
      'Bouncing at the bottom',
    ],
    alternatives: ['calf-raise', 'leg-press-calf-raise'],
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(
    (e) => e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle as never)
  );
}

export function getAlternatives(exercise: Exercise, equipment: string[], injuries: string[]): Exercise[] {
  return exercise.alternatives
    .map((id) => getExerciseById(id))
    .filter((e): e is Exercise => {
      if (!e) return false;
      const hasEquipment = e.equipment.some((eq) => equipment.includes(eq));
      const isSafe = !e.injuriesToAvoid.some((inj) => injuries.includes(inj));
      return hasEquipment && isSafe;
    })
    .slice(0, 5);
}
